name: perl-cpan-libraries-new

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/perl-cpan-libraries-new.yml"
      - ".github/scripts/get-libraries-list.sh"
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
      - master
      - "[2-9][0-9].[0-9][0-9].x"
    paths:
      - ".github/workflows/perl-cpan-libraries-new.yml"
      - ".github/scripts/get-libraries-list.sh"

jobs:
  get-environment:
    uses: ./.github/workflows/get-environment.yml

  libraries-check:
    needs: [get-environment]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.stability != 'stable'

    strategy:
      fail-fast: false
      matrix:
        distribution: [el8, el9, bullseye, bookworm, jammy, noble]
        include:
          - distribution: el8
            distribution_family: el
            distribution_version: 8
            image: almalinux:8
          - distribution: el9
            distribution_family: el
            distribution_version: 9
            image: almalinux:9
          - distribution: bullseye
            distribution_family: debian
            distribution_version: bullseye
            image: debian:bullseye
          - distribution: bookworm
            distribution_family: debian
            distribution_version: bookworm
            image: debian:bookworm
          - distribution: jammy
            distribution_family: ubuntu
            distribution_version: jammy
            image: ubuntu:jammy
          - distribution: noble
            distribution_family: ubuntu
            distribution_version: noble
            image: ubuntu:noble

    runs-on: ubuntu-24.04
    container:
      image: ${{ matrix.image }}

    name: Check CPAN libraries ${{ matrix.distribution }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up repositories
        run: |
          if [[ "${{ matrix.distribution_family }}" == "el" ]]; then
            dnf install -y epel-release 'dnf-command(config-manager)'
            dnf config-manager --set-enabled powertools || true # alma 8
            dnf config-manager --set-enabled crb || true # alma 9
            # Add Centreon repository
            echo -e '[centreon-plugins-stable]\n
            name=centreon plugins stable x86_64\n
            baseurl=https://packages.centreon.com/rpm-plugins/${{ matrix.distribution }}/stable/x86_64\n
            enabled=1\n
            gpgcheck=1\n
            gpgkey=https://yum-gpg.centreon.com/RPM-GPG-KEY-CES\n
            [centreon-plugins-stable-noarch]\n
            name=centreon plugins stable noarch\n
            baseurl=https://packages.centreon.com/rpm-plugins/${{ matrix.distribution }}/stable/noarch\n
            enabled=1\n
            gpgcheck=1\n
            gpgkey=https://yum-gpg.centreon.com/RPM-GPG-KEY-CES\n' > /etc/yum.repos.d/centreon-plugins.repo
          else
            apt-get update
            apt-get install -y wget gpg
            wget -O- https://apt-key.centreon.com | gpg --dearmor | tee /etc/apt/trusted.gpg.d/centreon.gpg > /dev/null 2>&1
            if [[ "${{ matrix.distribution_family }}" == "debian" ]]; then
              echo "deb https://packages.centreon.com/apt-plugins-stable/ ${{ matrix.distribution_version }} main" | tee /etc/apt/sources.list.d/centreon-plugins.list
            elif [[ "${{ matrix.distribution_family }}" == "ubuntu" ]]; then
              echo "deb https://packages.centreon.com/ubuntu-plugins-testing/ ${{ matrix.distribution_version }} main" | tee -a /etc/apt/sources.list.d/centreon-plugins.list
            fi
            apt-get update
          fi
        shell: bash

      - name: Get libraries list
        run: .github/scripts/get-cpan-libraries-list.sh ${{ matrix.distribution_family }} ${{ matrix.distribution_version }}
        shell: bash