name: perl-cpan-libraries-new

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/perl-cpan-libraries-new.yml"
      - ".github/scripts/get-libraries-list.sh"
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
      - master
      - "[2-9][0-9].[0-9][0-9].x"
    paths:
      - ".github/workflows/perl-cpan-libraries-new.yml"
      - ".github/scripts/get-libraries-list.sh"

jobs:
  get-environment:
    uses: ./.github/workflows/get-environment.yml

  libraries-check:
    needs: [get-environment]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.stability != 'stable'

    strategy:
      fail-fast: false
      matrix:
        distribution: [el8, el9, bullseye, bookworm, jammy, noble]
        include:
          - distribution: el8
            distribution_type: el
            distribution_version: 8
            image: almalinux:8
          - distribution: el9
            distribution_type: el
            distribution_version: 9
            image: almalinux:9
          - distribution: bullseye
            distribution_type: debian
            distribution_version: bullseye
            image: debian:bullseye
          - distribution: bookworm
            distribution_type: debian
            distribution_version: bookworm
            image: debian:bookworm
          - distribution: jammy
            distribution_type: ubuntu
            distribution_version: jammy
            image: ubuntu:jammy
          - distribution: noble
            distribution_type: ubuntu
            distribution_version: noble
            image: ubuntu:noble

    runs-on: ubuntu-24.04

    name: Check CPAN libraries ${{ matrix.distribution }}
    container:
      image: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.image }}:latest
      credentials:
        username: ${{ secrets.HARBOR_CENTREON_PULL_USERNAME }}
        password: ${{ secrets.HARBOR_CENTREON_PULL_TOKEN }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - if: ${{ matrix.distribution_type == 'el' }}
        name: Set up almalinux
        run: |
          dnf -y install epel-release
          dnf config-manager --set-enabled powertools

      - name: Get libraries list
        run: .github/scripts/get-libraries-list.sh ${{ matrix.distribution_type }} ${{ matrix.distribution_version }}