name: test-snmpsim

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test**'
      - 'src/**'
      - 'tests/functional/**'
      - 'tests/resources/mockoon/**'
      - 'tests/resources/snmp/**'

jobs:
  snmpsim-local:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: install libs
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt-get install -y libcurl4-openssl-dev snmp
          sudo apt-get install -qqy snmpsim
        shell: bash

      - name: Start snmpsim + snmpwalk
        run: |
          sudo useradd snmp
          sudo mkdir -p /usr/snmpsim/data
          sudo cp tests/resources/snmp/* /usr/snmpsim/data/
          snmpsimd --agent-udpv4-endpoint=127.0.0.1:2024 --process-user=snmp --process-group=snmp &
          snmpwalk -v2c -c os_linux_snmp_plugin 127.0.0.1:2024
        shell: bash
