name: test-container
on:
  workflow_dispatch:

jobs:
  docker-service:
    runs-on: ubuntu-22.04
    services:
      nginxservice:
        image: nginx
        ports:
          - 8080:80/tcp
      snmpsimservice:
        image: vklidu/snmpsim
        ports:
          - 161:161/udp

    steps:
      - name: install
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt-get install -y libcurl4-openssl-dev snmp
      - name: snmpwalk
        run: snmpwalk -v2c -c public 127.0.0.1:161
      - name: curl
        run: |
          apt install curl -y
          curl --version
          curl 127.0.0.1:8080
